### ISSUE TITLE
timstamp di notifikasi tidak sinkron

### ISSUE THREAD

**Issue by ihsangan** [salkuadrat/myousic-app#1]
saat lagu diputar, timestap tidak berjalan, saat di pause timstamp malah berjalan

> saat di pause

![Screenshot_2021-06-06-09-23-22](https://user-images.githubusercontent.com/63774886/120909725-800ce200-c6aa-11eb-8135-6767159971f1.png)

> saat di play

![Screenshot_2021-06-06-09-23-05](https://user-images.githubusercontent.com/63774886/120909727-8307d280-c6aa-11eb-9db3-1a8c1f2a45c3.png)

**Comment by salkuadrat** [comment]
Thanks for your feedback. Please update APK to version 1.1.0.
