### ISSUE TITLE
timestamp atas di notifikasi tidak sinkron

### ISSUE THREAD

**Issue by ananta-surya** [salkuadrat/myousic-app#2]
pada saat memutar lagu, timestamp atas berhenti di 00:00 sedangkan saat mati malah berjalan. timestamp bawah bekerja dengan baik.

![Screenshot_20210608_002819](https://user-images.githubusercontent.com/85513479/121064231-7fcb2e80-c7f1-11eb-85d4-fd8243a7c9dc.jpg)

![Screenshot_20210608_002927](https://user-images.githubusercontent.com/85513479/121064244-835eb580-c7f1-11eb-93df-9491508c7844.jpg)

**Comment by salkuadrat** [comment]
Coba tes lagi pakai versi 1.1.2 : [myousic-1.1.2.apk](https://github.com/salkuadrat/myousic-app/raw/master/myousic-1.1.2.apk)

Let me know if it's still not working.

**Comment by ananta-surya** [comment]
ah, it's working perfectly now. thanks for your hardwork!

![Screenshot_20210608_072839](https://user-images.githubusercontent.com/85513479/121103989-44e5ec80-c82b-11eb-863b-132e3d1eb189.jpg)
